bot.py
wxbot.py

- 可以回复自己
- 机器人回复内容加上"[Robot]"前缀
- 可以命令机器人开启或关闭

Make it reply to self 可以回复自己

---

wxbot.py

使用并修改了`pillow`的核心代码，简化`Windows`和`Mac`打开图片的方式

open image simple

---

wxbot.py

添加对 其他 系统的支持，简化 Mac 的命令

---

bot.py

add tuling123 news response content

---

wxbot.py

really optimize the code

---

wxbot.py

修改了下file的地址 
json内的filename调换下位置，只需要上传image/后面部分即可

fix upload_media can't send img problem

---

wxbot.py

测试的时候发现不一定都会上传成功
而成功时候 ['BaseResponse']['Ret'] 的值为0
如果两个都没成功则返回None

If the first upload failed attempt a second server

---

wxbot.py

修改生成的文件to本目录下的temp目录

---

wxbot.py

fix a bug when get group member name,  params order is  wrong

---

wxbot.py

test_sync_check函数完善，将4个服务器地址均放进去检测，得到合适的心跳服务器地址

修复1102，0和-1，-1的问题

---

wxbot.py

test_sync_check ，解决部分同学的sync接口不一样的问题，保持关注。

sync接口兼容 修复

---

wxbot.py

新增设置群聊名称接口--set_group_name

---

wxbot.py

fix a syntax

---

wxbot.py

1、更新心跳服务器获取方式，新增base_host
2、文件上传同步base_host
3、-1，-1错误的时候降低心跳获取频率

更新心跳服务器获取方式，同时修复文件可能上传失败的问题！ 在返回-1,-1时降低心跳获取频率！

---

wxbot.py

fix bugs~~~

---

test.py
wxbot.py

大概通讯录人数超过2500的时候，这个数字没有具体的测试，原来获取通讯录的方法就无法获取，这个分支在原来无法获取通讯录情况下，增加了一种获取的方法。

修复了通讯录过大，无法获取通讯录的问题

---

wxbot.py

修改保存wxid变量名写错

---

bot.py

修复无法转换'\xa0'‘字符问题

---

wxbot.py

应对由于群人数过多造成的无法直接添加用户到群、add_friend_to_group方法调用失败的情况。
将好友加入到群中。对人数多的群，需要调用add_friend_to_group方法。
拉人时，可以先尝试使用add_friend_to_group方法，当调用失败(Ret=1)时，再尝试调用此方法。

增加invite_friend_to_group方法

---

bot.py

In addition, how can we update the group info every time we receive message from this group?Thx.

fix bug that it can't find group personal name.

---

README.md
setup.py
wxbot/__init__.py
wxbot/bot.py
wxbot/test.py
wxbot/wxbot.py

* Compatible with python3 and python2.
* Restructure the directory to support install via `python setup.py install`.
* Support recovery before fresh login.

Support python3.

---

wxbot.py

Choose to add user or invite user into group by number of group member.
Add member directly if group member is less than 100 or send invite link to the user.

Add invite function for add user to group

---

wxbot.py

将WxbotManage中维护的属性和方法同步到Wxbot中，Wxbot以后只需要更新lib目录中的wxbot就能和官方同步

为了兼容WxbotManage，新增了一些属性和方法

---

README.md

新增WxbotManage系统介绍

---

wxbot.py

Fix the bug that after sending an image or file message the selector will be 2 forever util a text message was sent

Fix bugs that "infinite selector == 2" problem
